### ISSUE TITLE
Installing new effects on B1X Four doesn't work

### ISSUE THREAD

**Issue by fuzboxz** [mungewell/zoom-zt2#1]
First of all, thank you for making this!

I just tried a few new effects on my B1X Four and unfortunately they don't show up on the device at all. I can see them in zoom-zt2 GUI, but not on the device. Also, some effects show up in the file browser but not in the effects list in zoom-zt2 GUI. I tried it with both an empty and a factory state device, but none of them works. I tried looking for something similar to CMN_DRV.ZDL in ZD2 format, but I didn't find anything similar.

**Comment by fuzboxz** [comment]
Nevermind, I just realized reading that I have uploaded effects that take up multiple screens. Uploading 1U effects from G1X Four worked perfectly.

**Comment by mungewell** [comment]
Yes, I believe that the dual screen effects will be blocked by F/W using the 'guard.zt2' file.

Great news that other effects work for you.... I am excited for the new effects from the A1 Four but they've yet to release a F/W for that yet.
