### ISSUE TITLE
Turn the B1x in an G1x

### ISSUE THREAD

**Issue by roy-lueders** [mungewell/zoom-zt2#14]
Hi,

is there an Way to turn the B1x in an G1x (or for half of the Effects)?

And i saw over the cli i can get an Patch and save.
Is in plan that to do over the GUI?

**Comment by mungewell** [comment]
Hi Roy,
Not exactly sure which pedal(s) you have. If the B1X Four, then you can upload the effects from G1X Four (or vice versa). If you have the B1X/G1X then you could try looking at the sister project:
https://github.com/Barsik-Barbosik/Zoom-Firmware-Editor

No plans to do patch management in this app. Just to upload new effects, and understand the workings on the device.
