### ISSUE TITLE
Is it possible to open the WIKI up for documentation?

### ISSUE THREAD

**Issue by shooking** [mungewell/zoom-zt2#15]
Great stuff you are doing here.
Ideally I would love to contribute, especially to WIKI.

As you can see I have recently started on this.
All around the web is almost enough info on these pedals, but for various reasons hidden away or not collated.

My ultimate aim, now I realise this pedal works in midi, is to create a Ctrlr for it.
I am no GUI expert - but I am good with sysex, reverse engineering, hardware, porting and such stuff.

Instead of collecting and ranting in issues, with your permission I would love to update wiki pages.
With examples, explanations - a glossary so I can get on same page and use consistent nomenclature.

I am also curious about what happened to your G1 (to avoid hitting same issue :-().
If you were in UK I could drop you off a pedal.
I have a B1XFOUR and a G1XFOUR - now that I realise they can essentially do the same thing (it is the ZD2 / ZDL whatever --- see I need nomenclature!!) I dont necessarily need two.

I suspect like me you just get a kick out of looking for hidden Easter Eggs :-)

Best regards
shooking

**Comment by mungewell** [comment]
You also hinted at your age whilst saying "back in the day"... LOL. I'm no spring chicken either. And yes, I'm doing this as it's an interesting puzzle to figure out. _I should spend more time practicing bass though....._

My screen failed on the G1, probably as I took it apart many times - figured an FFC track cracked close to the connector. Still talks MIDI, just no screen output.

Let me think on the Wiki side, might like to establish a basic framework first.

**Comment by shooking** [comment]
Ah so you can still see the ASCII out - cool.
I noticed one command if sent repeatedly iterates thru .. but after a while
it breaks.

Now that I know you didn't brick your pedal by sysex I am more inclined to
get aggressive with the decoding.

Grounds rules is good - really I envisage a "De re Zoom" where the N sysex
headers are the title, some dry but patterns next then copious examples -
just like the 8 bit Atari or SunOS ...now that really dates me.

Also a way to discuss without necessarily going public but with intention
to distil into something public. Like majority of sysex is size 15. But
there are some short form size 8. When I find a 12 say .. am I missing 3
byes and Zoom is putting 00 00 00 in? These sorts of discussions.

I am a bit Asperger's and want to help witjout being dick or going into
too.much detail.

But as you said in the beginning - mostly I want to make music with these
and other pedals - and make hardware / software to assist.

Best regards
