### ISSUE TITLE
listing entire memory content for clean up

### ISSUE THREAD

**Issue by ZinnatBass** [mungewell/zoom-zt2#2]
In relation to my experience reported here: https://github.com/Barsik-Barbosik/Zoom-Firmware-Editor/issues/14#issuecomment-541579840

It would be great to have a command to list out the entire memory content, for clean up purposes.

Thanks!

**Comment by mungewell** [comment]
There is the ability to list the 'installed flles' via the wildcard command, this is used to fill the 'files' tab in the gui app.
https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2-gui.py#L269

Can you confirm whether this meets your request/suggestion?

**Comment by ZinnatBass** [comment]
Thanks for your quick answer! I see, so the wildcard command lists already everything. You can close this issue, sorry for the confusion.

I had misunderstood: I though the "Files" tab in the GUI was listing only the 'known' file extensions ('.raw', '.zt2', '.zd2'), and I was wondering whether there could be some 'temporary' file with some odd extension stuck in the memory. Out of curiosity, did you figured out why at some point you were stuck with 22% memory usage despite you had removed everything?

Meanwhile I think I have figured out the reason why my memory usage didn't seem to add up: most probably it was because when I messed up the 'FLST_SEQ.ZT2' I used Zoom Guitar Lab to inject from scratch the stock B1 effects, and that caused to install 1 or 2 extra effects which Zoom have released meanwhile for the B1, but were not available on my stock firmware.   

Once again, fantastic job, I'm cherishing your work more and more. Thank you!

**Comment by clint-toy** [comment]
I tried this with my B1xFour however it gets stuck at checksum error when adding an effect from G1xFour MS800.

**Comment by mungewell** [comment]
@clint-toy what exactly didn't work?
Can you maybe upload some logs/screen shots so we can figure it out...

**Comment by clint-toy** [comment]
Looks like I made a mistake in choosing the source effect to install.  Now,
the effects are installed however not showing in the pedal for editing.

**Comment by clint-toy** [comment]
Zoom Guitar Lab lists the added amps however saying missing effect when
loading to a patch
[image: image.png]

Effects List
[image: image.png]

**Comment by clint-toy** [comment]
This is resolved by using the Zoom Guitar Lab application to unload/delete the effects (they remain in the effects list like inactive status) and remove other effects to make room.  Then, add/install again the desired effects into the pedal.  Thanks!!! 

I think the zoomzt2 tool needs to have a flag if the device memory is already full or unable to load effects due to memory capacity.

**Comment by clint-toy** [comment]
@mungewell I believe if we edit the allow list 'FLST_SEQ.ZT2' to allow all effects to be installed, we can use the Zoom Guitar Lab to install/manage other effects and no longer need to extract from other firmwares.

**Comment by mungewell** [comment]
@clint-toy You might want to look at
https://www.zoom.co.jp/archive/ZDLM/AllZDL3.lst

**Comment by fuzboxz** [comment]
Experiencing a similar issue. I have a lot of files in the Files section which don't show up among the effects, probably FLST_SEQ.ZT2 inconsistency. Any easy way to get rid of these? Tried factory reset, firmware update or reuploading and deleting the files from the effects etc. On the last image you can see that there are no effects displayed however the leftovers still consume 54% of the memory.
![image](https://user-images.githubusercontent.com/5910566/72297885-322eae80-365d-11ea-840d-90f5ad365a01.png)
![image](https://user-images.githubusercontent.com/5910566/72297927-483c6f00-365d-11ea-8640-f2babd36d192.png)
![image](https://user-images.githubusercontent.com/5910566/72298211-e16b8580-365d-11ea-86b8-b39dd1304ddb.png)

**Comment by fuzboxz** [comment]
One way to solve leftover files for good is to reupload the file that's stuck and then delete it right away, but that's kind of slow.

**Comment by mungewell** [comment]
It's been a while, but the command line version ("zoomzt2.py") looks like it has an uninstall command.
```
    parser.add_option("-U", "--uninstall",
    help="Remove effect binary from attached device", dest="uninstall")
```

You could use that, or add similar functionality the to GUI. It calls'file_delete()' which in turns calls 'filename()'.
https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2.py#L353
https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2.py#L237

Not sure why (if intentional) I left this out of GUI, maybe a fear of someone removing a critical file.... take care!!

I'd also question why they are left there anyway.... maybe there's a bug in the GUI version.

**Comment by clint-toy** [comment]
Why not use the Zoom Guitar Lab to remove the effects instead of the zoom-zt2?

**Comment by fuzboxz** [comment]
@mungewell thanks, that solved the issue, I batch removed everything from B1X Four with the cli app. during the process i also realized that the latest packages don't work with zoom-zt2 as I always used the precompiled GUI exe previously. I'll make a requirements.txt and create a pull request when I have some free time. it might make sense to create another release that includes the cli exe as well.
@clint-toy unfortunately the leftover effects don't show up in Guitar Lab at all. look at the third screenshot.

**Comment by fuzboxz** [comment]
@clint-toy check out my download utility for the file that @mungewell referenced. using my script you can get all the effects for all devices with a single command. still work-in-progress but it can fetch all the effects, organize them and create device specific cleanup scripts that work with zoom-zt2. https://github.com/fuzboxz/zdownload

**Comment by clint-toy** [comment]
Thanks but i wouldnt know how to run py files.  Would you have anexe
perhaps or is it incorporated in mungwells exe?

**Comment by fuzboxz** [comment]
I will make an executable version of it as soon as it has a bit more functionality.

**Comment by clint-toy** [comment]
@fuzboxz do you have updates? :)

**Comment by shooking** [comment]
hey @fuzboxz 
Cool stuff - makes me wish I had a G5 now :-)

Just run your code - kinky.

Nice stuff inside a patch
divu.asm..... :.|
000050e0  00 c8 3a 00 00 2f 74 6d  70 2f 54 49 5f 4d 4b 4c  |..:../tmp/TI_MKL|
000050f0  49 42 79 46 54 6d 76 74  2f 53 52 43 00 54 4d 53  |IByFTmvt/SRC.TMS|
00005100  33 32 30 43 36 78 20 43  6f 6d 70 72 65 73 73 6f  |320C6x Compresso|
00005110  72 20 55 6e 69 78 20 76  37 2e 33 2e 34 20 43 6f  |r Unix v7.3.4 Co|
00005120  70 79 72 69 67 68 74 20  28 63 29 20 31 39 39 36  |pyright (c) 1996|
00005130  2d 32 30 31 32 20 54 65  78 61 73 20 49 6e 73 74  |-2012 Texas Inst|
00005140  72 75 6d 65 6e 74 73 20  49 6e 63 6f 72 70 6f 72  |ruments Incorpor|
00005150  61 74 65 64 00 01 02 c8  00 00 00 5f 5f 64 69 76  |ated.......__div|
00005160  75 00 20 3a 00 00 c8 3a  00 00 01 02 8f 00 5f 5f  |u. :...:......__|
00005170  64 69 76 75 00 01 01 54  49 20 4c 69 62 72 61 72  |divu...TI Librar|

Back in the day I used TMS32040's for Military R&D - nice to see they are cheap as chips these days.

Plus there are some hints on the parameters in the models

0000a2a0  00 00 00 00 00 00 01 00  00 00 50 52 4d 4a bd 04  |..........PRMJ..|
0000a2b0  00 00 7b 20 20 0d 0a 09  22 50 61 72 61 6d 65 74  |..{  ..."Paramet|
0000a2c0  65 72 73 22 3a 5b 20 20  0d 0a 09 09 7b 20 20 0d  |ers":[  ....{  .|
0000a2d0  0a 09 09 20 20 20 22 6e  61 6d 65 22 3a 22 42 61  |...   "name":"Ba|
0000a2e0  73 73 22 2c 0d 0a 09 09  20 20 20 22 65 78 70 6c  |ss",....   "expl|
0000a2f0  61 6e 61 74 69 6f 6e 22  3a 22 e4 bd 8e e5 9f 9f  |anation":"......|
0000a300  e3 81 ae e9 9f b3 e9 87  8f e3 82 92 e8 aa bf e7  |................|
0000a310  af 80 e3 81 97 e3 81 be  e3 81 99 e3 80 82 22 2c  |..............",|
0000a320  0d 0a 09 09 20 20 20 22  62 6c 61 63 6b 62 61 63  |....   "blackbac|
0000a330  6b 22 3a 66 61 6c 73 65  2c 0d 0a 09 09 20 20 20  |k":false,....   |
0000a340  22 70 65 64 61 6c 22 3a  66 61 6c 73 65 0d 0a 09  |"pedal":false...|
0000a350  09 7d 2c 0d 0a 09 09 7b  20 20 0d 0a 09 09 20 20  |.},....{  ....  |
0000a360  20 22 6e 61 6d 65 22 3a  22 4d 49 44 22 2c 0d 0a  | "name":"MID",..|
0000a370  09 09 20 20 20 22 65 78  70 6c 61 6e 61 74 69 6f  |..   "explanatio|
0000a380  6e 22 3a 22 e4 b8 ad e5  9f 9f e3 81 ae e9 9f b3  |n":"............|
0000a390  e9 87 8f e3 82 92 e8 aa  bf e7 af 80 e3 81 97 e3  |................|
0000a3a0  81 be e3 81 99 e3 80 82  22 2c 0d 0a 09 09 20 20  |........",....  |
0000a3b0  20 22 62 6c 61 63 6b 62  61 63 6b 22 3a 66 61 6c  | "blackback":fal|
0000a3c0  73 65 2c 0d 0a 09 09 20  20 20 22 70 65 64 61 6c  |se,....   "pedal|
0000a3d0  22 3a 66 61 6c 73 65 0d  0a 09 09 7d 2c 0d 0a 09  |":false....},...|
0000a3e0  09 7b 20 20 0d 0a 09 09  20 20 20 22 6e 61 6d 65  |.{  ....   "name|
0000a3f0  22 3a 22 54 72 65 62 6c  65 22 2c 0d 0a 09 09 20  |":"Treble",.... |
0000a400  20 20 22 65 78 70 6c 61  6e 61 74 69 6f 6e 22 3a  |  "explanation":|
0000a410  22 e9 ab 98 e5 9f 9f e3  81 ae e9 9f b3 e9 87 8f  |"...............|
0000a420  e3 82 92 e8 aa bf e7 af  80 e3 81 97 e3 81 be e3  |................|
0000a430  81 99 e3 80 82 22 2c 0d  0a 09 09 20 20 20 22 62  |.....",....   "b|
0000a440  6c 61 63 6b 62 61 63 6b  22 3a 66 61 6c 73 65 2c  |lackback":false,|
0000a450  0d 0a 09 09 20 20 20 22  70 65 64 61 6c 22 3a 66  |....   "pedal":f|
0000a460  61 6c 73 65 0d 0a 09 09  7d 2c 0d 0a 09 09 7b 20  |alse....},....{ |
0000a470  20 0d 0a 09 09 20 20 20  22 6e 61 6d 65 22 3a 22  | ....   "name":"|

and more gold

pi@raspberrypi:~/Software/zdownload/zoom_fx/G5n $ strings FD_TWINR.ZD2 
ZDLFx
1.20
FD TWNR
owAMP
ICON.
TXJ16
Fender Twin Reverb('65) 
TXE18
This models the sound of the Fender '65 Twin Reverb.
INFO
AMPAMP
BDATAR
...
PRMJ
	"Parameters":[  
		{  
		   "name":"Bass",
		   "explanation":"
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"MID",
		   "explanation":"
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"Treble",
		   "explanation":"
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"BRGHT",
		   "explanation":"
Gain
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"Gain",
		   "explanation":"
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"VOL",
		   "explanation":"
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"DEPTH",
		   "explanation":"
		   "blackback":true,
		   "pedal":false
		},
		{  
		   "name":"SPEED",
		   "explanation":"
		   "blackback":true,
		   "pedal":false
PRMEy
	"Parameters":[  
		{  
		   "name":"Bass",
		   "explanation":"Adjusts volume of low frequencies.",
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"MID",
		   "explanation":"Adjusts volume of middle frequencies.",
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"Treble",
		   "explanation":"Adjusts volume of high frequencies.",
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"BRGHT",
		   "explanation":"Sets the high frequency response. The effect is noticeable at lower gain settings.",
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"Gain",
		   "explanation":"Adjusts the gain.",
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"VOL",
		   "explanation":"Adjusts the volume.",
		   "blackback":false,
		   "pedal":false
		},
		{  
		   "name":"DEPTH",
		   "explanation":"Sets the depth of the modulation.",
		   "blackback":true,
		   "pedal":false
		},
		{  
		   "name":"SPEED",
		   "explanation":"Sets the speed of the modulation.",
		   "blackback":true,
		   "pedal":false
pi@raspberrypi:~/Software/zdownload/zoom_fx/G5n $ 

so nice. Might save me a bit of typing to create some JSON to store FX parameters/ranges.

Thanks.

**Comment by mungewell** [comment]
@shooking I had made a start at extracting information directly from ZD2, feel free to send patches ;-)
https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2.py#L66

**Comment by mungewell** [comment]
Closing, I have added the ability to enable a 'delete' button in the files tab. Use the '-D' flag on the command line to enable.

Use with care!!
