### ISSUE TITLE
Love this software! small issue with A1X file

### ISSUE THREAD

**Issue by kibit002** [mungewell/zoom-zt2#21]
Hi programmers,
I REALLY love this program thank you so much for creating it. Here's what I have. I have a G1X Four and I borrowed someone's A1X four. I'm an acoustic and electric player. I was able to upload some of the A1Xfour .zd2 files to my G1Xfour, but the ones I was interested wouldn't upload, seem they are all modeling files and begin with MDL_ I have also noticed on the A1Xfour there's a category for "AG MODEL" which isn't in the G1XFour. I'm getting this error (see pic) when I try to upload a MDL to my G1Xfour. I'm not programmer, I can understand some of it, but not much, could anything be done to make that work?? Thank You so much!! keep up the great work. ck.

![2020-12-29 12_23_46-Window](https://user-images.githubusercontent.com/75744931/103305903-f279e780-49d1-11eb-9490-81d4cd2241c4.png)

**Comment by mungewell** [comment]
Hi,
Thanks for the complements. I have actually been tinkering with A1Four effects on my G1Four before Christmas, and see that I made a ZIP with these changes rolled in but didn't upload.

Just pushed a release for you. Let me know whether it works you...
https://github.com/mungewell/zoom-zt2/releases/tag/v0.4.0

Happy New Year, glad to see the back of 2020. :-)

**Comment by kibit002** [comment]
Hi again! woo hoo, that works!! you have made my day!!!! many thanks again and have a happy new year!
![IMG_0881](https://user-images.githubusercontent.com/75744931/103309561-0a099e00-49db-11eb-8f68-489f10a5e409.jpg)

**Comment by mungewell** [comment]
Perfect, thanks for confirming.
