### ISSUE TITLE
Build V0.4 can not install effects

### ISSUE THREAD

**Issue by carrrlangas** [mungewell/zoom-zt2#27]
I get the following log when pressing "install". nothing happens on the pedal.

![image](https://user-images.githubusercontent.com/83246236/116613574-20981580-a939-11eb-9256-00dc136366bf.png)

**Comment by carrrlangas** [comment]
changed the file name to "PARAEQ2.zd2" so that it would have only 8 characters and it worked, "Effect installed".
But the pedal does not show the effect. Guitar tab shows it but when I try to added to a patch it says "missing effect"

My G1 Four hast firmware V2.0 and maybe that is conflicting with the ZoomZT2 program?

**Comment by mungewell** [comment]
Closing as you seem to have solution of naming file in 8.3 format
