### ISSUE TITLE
Derive parameters and ICON from Zoom pedal

### ISSUE THREAD

**Issue by shooking** [mungewell/zoom-zt2#29]
Hi Mungewell
I see you added some new functionality - ICON - is this pulling the bmp data out?
I modified your code to pull out the BMPs, the JSON for parameters/description and midi max values.
Alas the code isnt elegant.
I am sure you can do it much better.
Is this of any interest?

Best regards
Steve

**Comment by mungewell** [comment]
I already added a control for extracting/saving the BMP to disk. In theory we could also read from disk and insert a new icon into the ZD2.
https://github.com/mungewell/zoom-zt2/blob/master/decode_effect.py#L46

Adding the same for JSON is trivial. I have not looked at the content yet, but assume that it's easy to parse with element tree or the like.

The few Bytes after each of the 'name' and 'groupname' were a bit weird, I think they are just random padding - but not 100% sure.

**Comment by mungewell** [comment]
I already added a control for extracting/saving the BMP to disk. In theory we could also read from disk and insert a new icon into the ZD2.
https://github.com/mungewell/zoom-zt2/blob/master/decode_effect.py#L46

Adding the same for JSON is trivial. I have not looked at the content yet, but assume that it's easy to parse with element tree or the like.

The few Bytes after each of the 'name' and 'groupname' were a bit weird, I think they are just random padding - but not 100% sure.

**Comment by mungewell** [comment]
I already added a control for extracting/saving the BMP to disk. In theory we could also read from disk and insert a new icon into the ZD2.
https://github.com/mungewell/zoom-zt2/blob/master/decode_effect.py#L46

Adding the same for JSON is trivial. I have not looked at the content yet, but assume that it's easy to parse with element tree or the like.

The few Bytes after each of the 'name' and 'groupname' were a bit weird, I think they are just random padding - but not 100% sure.

**Comment by mungewell** [comment]
Closing as I've published v0.6.0 with the abilities to extract the various segments of the ZD2.
