### ISSUE TITLE
Support for new FW version 2.0?

### ISSUE THREAD

**Issue by vaesto** [mungewell/zoom-zt2#3]
Hello,
I've tried the script with new firmware, and it doesn't seem to work:
c:\temp\zoom\zoom-zt2-v0.2.0>python zoomzt2.py -R -w try1.tz2
('Checksum error', '0x34c74814')
('Checksum error', '0x41a9c8d4')
('Checksum error', '0x22225373')
('Checksum error', '0x2cc0d14f')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')
('Checksum error', '0x4d558a87')

c:\temp\zoom\zoom-zt2-v0.2.0>python zoomzt2.py -s try1.tz2
Traceback (most recent call last):
  File "zoomzt2.py", line 517, in <module>
    main()
  File "zoomzt2.py", line 466, in main
    config = ZT2.parse(data)
  File "C:\Python27\lib\site-packages\construct\core.py", line 304, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "C:\Python27\lib\site-packages\construct\core.py", line 316, in parse_str
eam
    return self._parsereport(stream, context, "(parsing)")
  File "C:\Python27\lib\site-packages\construct\core.py", line 328, in _parserep
ort
    obj = self._parse(stream, context, path)
  File "C:\Python27\lib\site-packages\construct\core.py", line 3881, in _parse
    stream_read(stream, pad)
  File "C:\Python27\lib\site-packages\construct\core.py", line 86, in stream_rea
d
    raise StreamError("stream read less then specified amount, expected %d, foun
d %d" % (length, len(data)))
construct.core.StreamError: stream read less then specified amount, expected 720
2, found 546

Alternatively, can you specify the exact versions of python, mido, construct and other modules used  in the script?

**Comment by vaesto** [comment]
Issue may be closed at the moment. I've found pre-compiled stuff deeper in the release. And it works.

**Comment by mungewell** [comment]
Glad you found the pre-built binaries. 

As you probably realized, I'm using Python3 on my machines.... maybe that is the issue.

**Comment by vaesto** [comment]
Yes. I see. I've tired Python3 as well, but then errors came from other packages. I guess the same exact versions need to used to get the results.
Anyway, thanks for a great project!
