### ISSUE TITLE
wxPython Exception 

### ISSUE THREAD

**Issue by Colatino** [mungewell/zoom-zt2#41]
I'm getting Exceptions while trying to run zoomgt2-gui.py:

> Horizontal alignment flags are ignored with wxEXPAND

Changing lines 94, 96 and 98 to the below fixed the issue (removed wx.ALIGN_CENTER):
```
94     sizer_4.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
96     sizer_5.Add(self.list_box_1, 0, wx.ALL | wx.EXPAND, 0)
98     sizer_6.Add(self.list_box_2, 0, wx.EXPAND, 0)
```
Running on windows 11, python 3.10.4, wxPython 4.1.1

**Comment by mungewell** [comment]
Thanks for the report. I'll question whether this is something to do with a new version of the wxPython or with something else.

Can you try the 'prebuilt' binary from the Releases section. This should have been built without external dependencies.

**Comment by Colatino** [comment]
The 'prebuilt' ran without issues

**Comment by mungewell** [comment]
Thanks for checking the binaries.

I confirmed I can manually remove these without noticeable issue, but I also remembered how the GUI part of the project was generated. I had used wxGlade to make the framework '.py' from the '.wxg' design.

This process is described here:
http://wxglade.sourceforge.net/docs/source_code.html

I note that there's a build option for `2.8` or `3.10`, I don't know whether that was an option back then....
https://github.com/mungewell/zoom-zt2/blob/master/zoomzt2-gui.py#L4
`# generated by wxGlade 0.8.0 on Sun Sep 15 09:53:08 2019`

Manually removing these flags is probably OK, but I'll try re-rendering the design for `3.10` and see how different it is...
https://packages.ubuntu.com/impish/wxglade

**Comment by mungewell** [comment]
try the code on this branch.... I had to go back and change/update the `.wgx` source as well.
https://github.com/mungewell/zoom-zt2/tree/wx_update

Auto-generated code does not now have `ALIGN_CENTER`.

**Comment by Colatino** [comment]
Now the GUI opens but I still had to use the solution on issue #42

**Comment by mungewell** [comment]
Yes, one bug at a time... ;-)

I'll merge these changes in, but will need to do some upgrading on my Windows box to figure out Mido.

**Comment by mungewell** [comment]
Merged to Main.
