### ISSUE TITLE
Empty effects list but 90% memory used

### ISSUE THREAD

**Issue by blurenciel** [mungewell/zoom-zt2#60]
Hi. I got one problem. It happened yesterday when i tried installing pedal pitch shift effect to my g1four. In the effects tab, nothing is listed, but in zoom guitar lab, it shows around 90% memory used.
![zt2_fx_tab](https://user-images.githubusercontent.com/4011146/226957227-24a32f76-eba8-4c03-9029-5605f2360273.png)
This is the empty effects list
![zoom_gl_fx_tab](https://user-images.githubusercontent.com/4011146/226957271-150ad9d1-291c-49f8-a24b-42505a82dd44.png)
this is guitar lab screen.

any means to view the 90% used memory? .. and how to use them again. thanks.

**Comment by mungewell** [comment]
If you look on the 'Files' tab do you see a load of files, I had an 'incident' where I had accidently added the same file lots(!!) of times and filled the memory,

If the app is started (from the command line) with the '-d' flag, then an extra 'delete' button will appear on the 'files' tab. Use with care, not sure if you can brick by deleting wrong file(s). Should be OK to delete any 'ZD2' file.

**Comment by blurenciel** [comment]
Super nice. Works like charm. now i can only load and unload effects through zt2. i tried loading using zoom guitar lab but the files are listed yet the effects appear missing on the hardware. Many thanks!
