### ISSUE TITLE
Lo/Mid/Hi tone/Volume commands 

### ISSUE THREAD

**Issue by fm-sys** [mungewell/zoom-zt2#62]
Hi, the Readme mentions that it is possible to adjust Lo/Mid/Hi tone, and Volume after entering PC mode.

Does anyone know which commands do I need to send to change these params via the USB connection?

I own a G1four if that matters...

**Comment by nomadbyte** [comment]
> ...adjust Lo/Mid/Hi tone, and Volume

Do you mean the built-in EQ controls as opposed to effect params in a patch?

**Comment by fm-sys** [comment]
> Do you mean the built-in Output EQ controls, as opposed to effect-level params in a patch?

Yes, exactly.

> So, likely the firmware does not expect any external Sysex for these controls

Hm, ok. Not what I wanted to hear, but thanks for your help!
