### ISSUE TITLE
Is there any way to quickly restore default effect list on G1four?

### ISSUE THREAD

**Issue by pan-danio** [mungewell/zoom-zt2#65]
Hey, im planning to sell my zoom g1four and i want to restore default fx list on my unit. Is there any quick method to do that? I want to delete all my added effecsts and install all missing from factory.
I tried installing firmware once again, and initializing my unit. I have now default patches list, but some patches has excalmation mark in the chain, so no every effect is loaded. 
The bad thing is guitar lab shows 99% memory usage of the unit. 
Tried to use "G1_purge.sh" script in the scripts folder, modified it to ".bat" (im using windows) but every line i get and error:
eg. `python zoomzt2.py -U UK30A_1U.ZD2 -S empty.zt2` gives me `zoomzt2: error: unrecognized arguments: empty.zt2`
The `empty.zt2` is present in local folder.

Maybe there is an easy solution for that?

**Comment by mungewell** [comment]
That script is 3yrs old, and perhaps is out of date with main program.

The fact that GL is reporting 99% space use suggests that the actual ZD2 files have not been removed. You can start the GUI app with the `-D` flag to enable a delete button on the files tab... which you can then use to manually delete files.
```
    parser.add_argument("-D", "--delete",
        help="enable button to delete files from device (use with care)",
        action="store_true", dest="delete")
```

Or alternately you can use `xargs` to pass multiple effect file names to the command line script. I'm away from my pedal, but that would look something like
```
$ ls *.ZD2 | xargs python3 zoom-zt2.py --uninstall 
```
or
```
$ cut -f 6 scripts/G1_everything.sh | xargs python3 zoom-zt2.py --uninstall 
```

**Comment by pan-danio** [comment]
Ok, thx for your answer. I have few more questions though:

1) Does `G1_everything.sh` script uploads all the default effects on g1?
2) I ran GUI with -D flag and i have "delete" button available. What is the difference from "Delete" btn on "Files" tab and "Remove" btn on "effects" tab?

**Comment by nomadbyte** [comment]
"Remove" is to uninstall an effect, which deletes the effect's ZD2 file from the pedal internal storage and removes a reference to the effect from the internal effect list file (`FLST_SEQ.ZT2`). "Delete" is just that, delete a file.

**Comment by nomadbyte** [comment]
For G1 FOUR, the default effect list:

|filename|name
|-|-
|COMP.ZD2|Comp
|RACKCOMP.ZD2|RackComp
|SLWATK.ZD2|SlowATTCK
|ZNR.ZD2|ZNR
|GRAYCOMP.ZD2|GrayComp
|LMT1176.ZD2|LMT-76
|AUTOWAH.ZD2|AutoWah
|SEQFLTR.ZD2|SeqFLTR
|GTGEQ71U.ZD2|Gt GEQ 7
|PARAEQ.ZD2|ParaEQ
|RNDMFLTR.ZD2|RndmFLTR
|TS_DRIVE.ZD2|TS Drive
|EP_STOMP.ZD2|EP Stomp
|RCBOOST.ZD2|RC Boost
|GOLD_DRV.ZD2|GoldDrive
|SWEETDRV.ZD2|SweetDrv
|DYNDRIVE.ZD2|DYN Drive
|REDCRUNC.ZD2|RedCrunch
|ACOSIM.ZD2|Aco.Sim
|NYC_MUFF.ZD2|NYC Muff
|BGTHRTTL.ZD2|HG THRTTL
|DIST_1.ZD2|DIST 1
|SQUEAK.ZD2|Squeak
|DISTPLUS.ZD2|DIST Plus
|ZEN_DRV.ZD2|Zen O.DRV
|VIOLETDS.ZD2|VioletDST
|MS800_1U.ZD2|MS 800
|MS19591U.ZD2|MS 1959
|FD_TWR1U.ZD2|FD TWNR
|FDBMAN1U.ZD2|FD B-MAN
|FDDLXR1U.ZD2|FD DLXR
|UK30A_1U.ZD2|UK 30A
|BGMK1_1U.ZD2|BG MK1
|XTSBLU1U.ZD2|XtasyBlue
|HW100_1U.ZD2|HW 100
|RCTORG1U.ZD2|Recti ORG
|ORG1201U.ZD2|ORG120
|DZ_DRV1U.ZD2|DZ DRV
|MACH301U.ZD2|MATCH30
|MS4X12.ZD2|MS4x12
|MS4X12GB.ZD2|MS4x12GB
|FD2X12.ZD2|FD2x12
|FDB4X10.ZD2|FD-B4x10
|FDDX1X12.ZD2|FD-DX1x12
|UK2X12.ZD2|UK2x12
|MK1_1X12.ZD2|MK1 1x12
|BGN4X12.ZD2|BGN4x12
|HW4X12.ZD2|HW4x12
|RCT4X12.ZD2|RCT4x12
|ORG_4X12.ZD2|ORG4x12
|DZ4X12F.ZD2|DZ4x12F
|MA2X12.ZD2|MA2x12
|TREMOLO.ZD2|Tremolo
|STEREOCH.ZD2|StereoCho
|PHASER.ZD2|Phaser
|VINFLNGR.ZD2|VinFLNGR
|THEVIBE.ZD2|TheVibe
|VIBRATO.ZD2|Vibrato
|OCTAVE.ZD2|Octave
|PITCHSHF.ZD2|PitchSHFT
|HPS.ZD2|HPS
|CLONECHO.ZD2|CloneCho
|CRNTRI3S.ZD2|CoronaTri
|BOMBER.ZD2|Bomber
|HOTSPICE.ZD2|HotSpice
|DELAY_3S.ZD2|Delay
|ANDLY_3S.ZD2|AnalogDly
|TAPEECHO.ZD2|TapeEcho
|RVRSDL3S.ZD2|ReverseDL
|MODDELAY.ZD2|ModDelay
|PPDLY_3S.ZD2|P-P Delay
|SOFTEC3S.ZD2|SoftEcho
|ROOM.ZD2|Room
|HALL.ZD2|Hall
|HD_HALL.ZD2|HD Hall
|SPRING.ZD2|Spring
|FDSPRING.ZD2|FD Spring
|PLATEREV.ZD2|Plate

When the corresponding effect list file (`FLST_SEQ.ZT2`) is missing, it will be regenerated automatically on boot up; all .ZD2 files found will be referenced.

NOTE: do NOT delete all files from, only .ZD2; other files (.raw, .BDL) must be present for proper functioning of the pedal.

**Comment by mungewell** [comment]
In order to 'reset' the pedal you can use `zoomzt2.py` to remove all the effects, and then upload the default `FLST_SEQ.ZT2` file. Guitar-Lab will then 'auto-magically' install all required effect files when the pedal is connected.

The 'FLST_SEQ.ZT2` file can be found in the unzipped FW from the appropriate pedal, or I have uploaded some 'build' scripts to effect directory... for example:
https://github.com/mungewell/zoom-zt2/blob/master/zoom_fx_AllZDL7/G1%20FOUR/unzipped/FLST_SEQ.sh

To use the script method
```
$ cp EMPTY.ZT2 FLST_SEQ.ZT2
$ sh FLST_SEQ.sh
$ python3 zoomzt2.py -S FLST_SEQ.ZT2
```

**Comment by pan-danio** [comment]
Thx for your help Guys. I've done this by hand. I carefully checked this default effect list and list from my effect. Then i deleted all the unwanted effects and installed the missing ones. Case closed.
